#!/bin/bash

email_contents="/mnt/volume1/logging/notifications/zfs_allocated_details.txt"
echo "" > "$email_contents"

echo "---------------------------------------------------" >> "$email_contents"
echo "VOLUME1 ZFS ALLOCATION DETAILS" >> "$email_contents"
echo "---------------------------------------------------" >> "$email_contents"
echo "" >> "$email_contents"
echo "$(zfs list volume1 -r -o name,recordsize,refer,usedbysnapshots,used,avail,compression,compressratio,mountpoint)" >> "$email_contents"
echo "" >> "$email_contents"
echo "" >> "$email_contents"
echo "---------------------------------------------------" >> "$email_contents"
echo "VOLUME2 ZFS ALLOCATION DETAILS" >> "$email_contents"
echo "---------------------------------------------------" >> "$email_contents"
echo "" >> "$email_contents"
echo "$(zfs list volume2 -r -o name,recordsize,refer,usedbysnapshots,used,avail,compression,compressratio,mountpoint)" >> "$email_contents"
echo "" >> "$email_contents"
echo "" >> "$email_contents"
echo "---------------------------------------------------" >> "$email_contents"
echo "VOLUME3 ZFS ALLOCATION DETAILS" >> "$email_contents"
echo "---------------------------------------------------" >> "$email_contents"
echo "" >> "$email_contents"
echo "$(zfs list volume3 -r -o name,recordsize,refer,usedbysnapshots,used,avail,compression,compressratio,mountpoint)" >> "$email_contents"
echo "" >> "$email_contents"
echo "" >> "$email_contents"
echo "---------------------------------------------------" >> "$email_contents"
echo "VOLUME5 ZFS ALLOCATION DETAILS" >> "$email_contents"
echo "---------------------------------------------------" >> "$email_contents"
echo "" >> "$email_contents"
echo "$(zfs list volume5 -r -o name,recordsize,refer,usedbysnapshots,used,avail,compression,compressratio,mountpoint)" >> "$email_contents"


python3 /mnt/volume1/logging/multireport_sendemail.py --subject "ZFS Allocation Status" --to_address "email@email.com" --mail_body_html "ZFS ALLOCATION STATUS" --override_fromemail "email@email.com" --attachment_files "$email_contents"
