services:
  radarr:
    container_name: radarr
    environment:
      - PUID=3012
      - PGID=3012
      - TZ=America/Chicago
    image: lscr.io/linuxserver/radarr:latest
    network_mode: container:gluetun
    restart: unless-stopped
    volumes:
      - /mnt/volume1/apps/radarr/config:/config
      - /mnt/volume1/apps/radarr/downloads:/downloads
