services:
  mysql:
    environment:
      MYSQL_DATABASE: home
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_USER: brian
      PGID: 3005
      PUID: 3006
    image: mysql:latest
    ports:
      - '3306:3306'
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /mnt/volume1/hosting/sql:/var/lib/mysql   #Docker will create the volume for you in the /var/lib/docker/volumes folder.
  nginx:
    depends_on:
      - php
    environment:
      PGID: 3005
      PUID: 3006
    image: nginx:latest
    links:
      - php
    ports:
      - '81:80'
      - '444:443'
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /mnt/volume1/hosting/web:/var/www/html:rw
      - /mnt/volume1/hosting/nginx:/etc/nginx/conf.d:rw
  php:
    build:
      dockerfile: /mnt/volume1/hosting/php-dockerfile
    depends_on:
      - mysql
    environment:
      PGID: 3005
      PUID: 3006
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /mnt/volume1/hosting/web:/var/www/html:rw
  phpmyadmin:
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: password1
      PGID: 3005
      PMA_HOST: mysql
      PUID: 3006
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '82:80'
    pull_policy: always
    restart: unless-stopped
