services:
  chromium-normal:
    environment:
      CUSTOM_USER: user
      PASSWORD: password
      PGID: 3001
      PUID: 3001
      TITLE: Chromium-Normal
      TZ: Chicago
    image: ghcr.io/linuxserver/chromium:latest
    ports:
      - '3411:3001'
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    shm_size: 1g
    volumes:
      - /mnt/volume1/apps/chromiumnormal:/config:rw
