services:
  doublecommander:
    cap_drop:
      - NET_RAW
      - NET_ADMIN
    container_name: Double-Commander
    dns:
      - 0.0.0.0
    environment:
      CUSTOM_USER: user
      PASSWORD: password
      PGID: 3003
      PUID: 3003
      TZ: America/Chicago
    image: lscr.io/linuxserver/doublecommander:latest
    ports:
      - '3278:3000'
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /mnt/volume1/apps/doublecommander/config:/config:rw
      - /mnt/volume1/apps/doublecommander/data:/data:rw
      - /mnt/volume1:/volume1:rw
      - /mnt/volume2:/volume2:rw
      - /mnt/volume3:/volume3:rw
      - /mnt/volume5:/volume5:rw
